### PR TITLE
home page is now responsive for mobile view, and added signup and sig…

### PR DESCRIPTION
**Pull request by mpa-LHutchinson**
…nin buttons to homepage

The picture now adjusts properly for the mobile view, and I also added some options on the homepage for the user to either signup or login. Both right now just take the user to the login page. Let me know if you'd like me to add more to the home page.

after

### CODE REVIEW

**Comment by TheBaljitSingh** [comment]
Remove the Login/Signup Buttons from homepage (not required because Login button given on top right of Navbar)

**Comment by mpa-LHutchinson** [comment]
@TheBaljitSingh can you add the "hacktoberfest-accepted" label to this PR so it gets accepted for hacktoberfest?

**Comment by mpa-LHutchinson** [comment]
@TheBaljitSingh can you add the label "hacktoberfest-accepted" to this

**Comment by TheBaljitSingh** [comment]
Only 'hacktoberfest' mentioned to their website

**Comment by mpa-LHutchinson** [comment]
"Maintainers need to add the hacktoberfest topic to the repository, or add the hacktoberfest-accepted label to you PR." Is what it says when I hover over this PR.

**Pull request merged**
