### PR TITLE
Fix:Responsivness of login and signup page

### LINKED ISSUE #5: Login and Sign up page is not responsive
- Both pages are not responsive, can you make it

### PR DESCRIPTION
**Pull request by prashantrai-30**
This PR will resolve #5

### CODE REVIEW

**Comment by prashantrai-30** [comment]
Hey @TheBaljitSingh,
Can you check and want any changes :)

**Comment by TheBaljitSingh** [comment]
Changes - on the sign up page for Create an Account button should contain full weights (for larger than mobile devices)

And don't make another commit. Modify this Commit only

**Comment by prashantrai-30** [comment]
weight or width ??

**Comment by TheBaljitSingh** [comment]
> weight or width ??
My bad: it's width

**Comment by prashantrai-30** [comment]
@TheBaljitSingh can you check now :)

**Comment by TheBaljitSingh** [comment]
Better if 'create an account' goes in single row

> @TheBaljitSingh can you check now :)

**Comment by prashantrai-30** [comment]
screenshot is not visible

**Comment by TheBaljitSingh** [comment]
> 
> Better if 'create an account' goes in single row
> 
> > @TheBaljitSingh can you check now :)
> 
> 
Can you add 'or' on the login page.
Like login or sign in with Google

**Comment by prashantrai-30** [comment]
I don't understand what you want to say.

**Comment by TheBaljitSingh** [comment]
> I don't understand what you want to say.

A horizontal bar with OR between 'login' button and 'sign in with Google' button

**Comment by prashantrai-30** [comment]
what do you want "OR" or horizontal bar

**Comment by TheBaljitSingh** [comment]
> what do you want "OR" or horizontal bar
>

**Comment by prashantrai-30** [comment]
please tell do you want any other changes except this :)

**Comment by TheBaljitSingh** [comment]
> please tell do you want any other changes except this :)

If you don't want to try. Let me know I will merge it and close these issues.

Anyways great contribution. 👍

**Comment by prashantrai-30** [comment]
@TheBaljitSingh you can merge and close this issue :)

**Pull request merged**
